apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: questionario
  labels:
    app: backend
spec:
  replicas: 4
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: luqui25/lucas-fluminense-backend:latest
          ports:
            - containerPort: 8080
          env:
            - name: ASPNETCORE_ENVIRONMENT
              value: "Development"
            - name: ConnectionStrings__DefaultConnection
              valueFrom:
                secretKeyRef:
                  name: questionario-secrets
                  key: MONGO_CONNECTION_STRING
            - name: MongoDB__DatabaseName
              valueFrom:
                secretKeyRef:
                  name: questionario-secrets
                  key: MONGO_DATABASE
            - name: RabbitMQ__HostName
              value: "rabbitmq"
            - name: RabbitMQ__UserName
              valueFrom:
                secretKeyRef:
                  name: questionario-secrets
                  key: RABBITMQ_DEFAULT_USER
            - name: RabbitMQ__Password
              valueFrom:
                secretKeyRef:
                  name: questionario-secrets
                  key: RABBITMQ_DEFAULT_PASS
          readinessProbe:
            httpGet:
              path: /api/questionario
              port: 8080
            initialDelaySeconds: 15
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /api/questionario
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 15
---
apiVersion: v1
kind: Service
metadata:
  name: backend
  namespace: questionario
spec:
  selector:
    app: backend
  ports:
    - port: 5000
      targetPort: 8080
      nodePort: 30500
  type: NodePort