apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

generatorOptions:
  disableNameSuffixHash: true

configMapGenerator:
  - name: grafana-dashboard
    namespace: questionario
    files:
      - kubernetes.json=base/monitoring/kubernetes-dashboard.json

resources:
  - base/namespace.yaml
  - base/secrets.yaml
  - base/database/mongodb.yaml
  - base/database/rabbitmq.yaml
  - base/application/backend.yaml
  - base/application/frontend.yaml
  - base/monitoring/kube-state-metrics.yaml
  - base/monitoring/prometheus.yaml
  - base/monitoring/grafana.yaml